name: nutrinutri
description: "Your Personal AI Nutritionist. Simple. Private. Open Source. Not-for-profit."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  cupertino_icons: ^1.0.8
  drift: ^2.31.0
  drift_flutter: ^0.2.8
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  go_router: ^17.1.0
  google_fonts: ^8.0.1
  google_sign_in_all_platforms: ^2.0.2
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  path: ^1.9.0
  riverpod_annotation: ^4.0.2
  sqlite3_flutter_libs: ^0.5.20
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.11.0
  drift_dev: ^2.31.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^4.0.3

dependency_overrides:
  test_api: ^0.7.9

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/nutrinutri.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/nutrinutri.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/nutrinutri.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/nutrinutri.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/nutrinutri.svg
    - assets/images/nutrinutri.png
    - assets/images/nutrinutri-frame.svg
    - assets/images/nutrinutri-frame.png
