name: nutrinutri
description: "Your Personal AI Nutritionist. Simple. Private. Open Source. Not-for-profit."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  cupertino_icons: ^1.0.8
  extension_google_sign_in_as_googleapis_auth: ^2.0.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  gap: ^3.0.1
  go_router: ^14.6.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  path: ^1.9.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.5
  sqflite: ^2.4.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true
