name: nutrinutri
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^14.6.0

  # Google & Sync
  extension_google_sign_in_as_googleapis_auth: ^2.0.0
  google_sign_in: ^6.2.1
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0

  # Database
  sqflite: ^2.4.1
  path: ^1.9.0

  # JSON & Serialization
  json_annotation: ^4.9.0

  # Utils
  intl: ^0.20.2
  uuid: ^4.5.1
  shared_preferences: ^2.3.5

  # UI
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  fl_chart: ^0.69.0
  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  url_launcher: ^6.3.1

  # AI
  http: ^1.2.2

  # Camera & Image
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  riverpod_generator: ^2.6.3
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
